[target.aarch64-linux-android]
rustflags = ["-C", "link-arg=-z", "-C", "link-arg=max-page-size=16384"]

[target.armv7-linux-androideabi]
rustflags = ["-C", "link-arg=-z", "-C", "link-arg=max-page-size=16384"]

[env]
BINDGEN_EXTRA_CLANG_ARGS_armv7_linux_androideabi = "--sysroot=/home/ben/Android/Sdk/ndk/27.2.12479018/toolchains/llvm/prebuilt/linux-x86_64/sysroot"
